version: "3"


services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment: 
      - POSTGRES_PASSWORD=devpass
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis
    volumes:
     - $PWD/redis-data:/var/lib/redis
    ports:
      - "6379:6379"

  web:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - MY_EMAIL_PASSWORD=""
      - MY_EMAIL=""
    volumes: 
      - ./project:/project
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


  worker:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - MY_EMAIL_PASSWORD=""
      - MY_EMAIL=''
    volumes: 
      - ./project:/project
    depends_on:
      - redis
      - postgresdb
    build:
      context: ./project
      dockerfile: DockerfileCelery
    command: [ "celery","-A","config" ,"worker" ,"--loglevel=info" ]
      
  nginx:
    restart: always
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes: 
      - ./project/static/:/static
      - ./project/media/:/media
    depends_on: 
      - postgresdb
      - web
      - worker
    ports: 
      - "80:80"