version: "3"


services:
  web:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - MY_EMAIL_PASSWORD=""
      - MY_EMAIL=""
    volumes: 
      - ./project:/project
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    network_mode: host


  worker:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - MY_EMAIL_PASSWORD=""
      - MY_EMAIL=''
    volumes: 
      - ./project:/project
    build:
      context: ./project
      dockerfile: DockerfileCelery
    command: [ "celery","-A","config" ,"worker" ,"--loglevel=info" ]
    network_mode: host
