version: "3"


services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"

  web:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.pro
    volumes: 
      - ./project:/project
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


  worker:
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.pro
    depends_on:
      - redis
    build:
      context: ./project
      dockerfile: DockerfileCelery
    command: [ "celery","-A","config" ,"worker" ,"--loglevel=info" ]
      
  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes: 
      - ./project/static/:/static
      - ./project/media/:/media

    depends_on: 
      - web
    ports: 
      - "80:80"